version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/golang:1.9
        environment:
          PRODUCTION: "true"
    working_directory: /go/src/github.com/mosvector/go-cicd-example
  restore_repo: &restore_repo
    restore_cache:
      key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/mosvector/go-cicd-example
  test:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: Run test
          command: go vet
      - run:
          name: Run cover test
          command: go test -v -cover
  build:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: Build app
          command: go build

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
            - build
