version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/mosvector/go-cicd-example
    steps:
      - checkout
      - run: go vet
      - run: go test -v -cover
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/mosvector/go-cicd-example
    steps:
      - checkout
      - run: go build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
